# Generated by Django 5.2.4 on 2026-01-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='date',
        ),
    ]
