# Generated by Django 5.2.4 on 2026-01-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0003_articlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
