# Generated by Django 5.2.4 on 2026-01-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0004_articlepage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='intro',
            field=models.CharField(max_length=225),
        ),
    ]
